-- Quick Copy-Paste SQL Queries for Sample Spare Parts Data

INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Ball Bearing 6205', 'spare part', 'SKF', '6205-2Z', '150.00', '250.00', 45, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Drive Belt', 'spare part', 'Dunlop', 'X-Series', '200.00', '350.00', 32, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Motor Coupling', 'spare part', 'Lovejoy', 'L-075', '300.00', '500.00', 28, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Roller Chain', 'spare part', 'Renold', '#40', '120.00', '200.00', 56, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Gear Set', 'spare parts', 'Flender', 'MV-60', '450.00', '800.00', 15, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Oil Seal Kit', 'spare part', 'Freudenberg', 'Standard', '80.00', '150.00', 72, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Bearing Bracket', 'spare parts', 'Viking', 'UCP-208', '250.00', '450.00', 22, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Shaft Coupling', 'spare part', 'Rexnord', 'Style RC', '180.00', '320.00', 38, 'Warehouse A', 'used');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Pulley 75mm', 'spare part', 'Martin', 'PS', '95.00', '180.00', 64, 'Warehouse C', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Thrust Washer', 'spare parts', 'INA', '', '25.00', '50.00', 120, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('V-Belt A-Section', 'spare part', 'Bando', 'A-3600', '75.00', '140.00', 85, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Grease Cartridge', 'spare parts', 'Shell', 'Gadus S2', '65.00', '120.00', 150, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Power Cord 10A', 'spare part', 'Crompton', 'Industrial', '110.00', '200.00', 42, 'Warehouse C', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Connector Box', 'spare parts', 'Legrand', 'Plexo', '95.00', '170.00', 68, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Thermostat Switch', 'spare part', 'Honeywell', 'T87', '135.00', '250.00', 19, 'Warehouse D', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Precision Shaft', 'spare part', 'Timken', 'PS-260', '1200.00', '2000.00', 3, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Gearbox Seal', 'spare parts', 'Corteco', 'HQ820', '165.00', '300.00', 2, 'Warehouse C', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Spring Assembly', 'spare part', 'Lesjöfors', 'Compression', '140.00', '250.00', 5, 'Warehouse A', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Motor Brush Set', 'spare parts', 'Mersen', 'Carbon', '220.00', '400.00', 4, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Filter Element', 'spare part', 'Hydac', 'FES-160', '320.00', '550.00', 1, 'Warehouse C', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Hydraulic Pump', 'spare parts', 'Bosch Rexroth', 'A2FO', '2500.00', '4200.00', 0, 'Warehouse B', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Solenoid Valve', 'spare part', 'Moog', 'D956-2025', '450.00', '750.00', 0, 'Warehouse D', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Contactor Coil', 'spare parts', 'ABB', 'ZA95', '180.00', '320.00', 0, 'Warehouse C', 'new');
INSERT INTO machines (name, category, brand, model, purchase_price, selling_price, quantity, location, condition) VALUES ('Circuit Breaker', 'spare part', 'Siemens', '3SL1', '280.00', '500.00', 0, 'Warehouse D', 'refurbished');
